/**
 * This code was generated by Builder.io.
 */

 // @ts-ignore
import * as React from "react";
import Counter from './Counter/Counter'

function MyComponent() {
  return (
    <>
      <div
        className="flex flex-col shrink-0 box-border min-h-[100px] ml-[calc(50%_-_50vw)] text-black bg-white w-screen pt-8 pb-20 px-5 max-sm:pb-10"
      >
        <section className="flex flex-col shrink-0 box-border min-h-[100px] text-black bg-white w-full self-stretch grow max-w-[1200px] items-stretch mx-auto pt-8 pb-20 px-5 max-sm:pb-10">
          <div className="flex flex-col relative shrink-0 box-border items-center px-5">
            <div className="relative shrink-0 box-border h-auto text-black font-semibold text-3xl text-center w-full max-w-[500px] mt-5">
              <p>Testing builder.io</p>
            </div>
            <div className="flex flex-row relative shrink-0 box-border justify-center gap-7">
              <img
                loading="lazy"
                sizes="(max-width: 638px) 8vw, (max-width: 998px) 6vw, 4vw"
                src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F7bca7936d0a54d568dc5da34f4aaa5af?width=50"
                className="aspect-square object-contain object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden max-w-[50px]"
              />
              <div className="relative shrink-0 box-border h-auto text-black text-3xl font-light w-auto self-center">
                <p>+</p>
              </div>
              <img
                loading="lazy"
                sizes="(max-width: 638px) 7vw, (max-width: 998px) 4vw, 3vw"
                src="https://cdn.builder.io/api/v1/image/assets%2F8d9ee72a33344b4b867918b442ebd0af%2F674df6ccd3c94f29bf67d9a8e5b00e08?width=39"
                className="aspect-[0.88] object-contain object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden max-w-[39px]"
              />
            </div>
          </div>
          <div className="flex flex-row relative shrink-0 box-border justify-center w-full self-center max-w-[700px] gap-10 mt-20 max-sm:flex max-sm:flex-col max-sm:items-center">
            <div className="flex flex-col relative shrink-0 box-border justify-center max-w-[50%] text-black pl-5 max-sm:items-center max-sm:max-w-[300px]">
              <div className="relative shrink-0 box-border h-auto text-black font-semibold text-left mb-2.5">
                <p>Compose with your components</p>
              </div>
              <div className="relative shrink-0 box-border h-auto text-black text-left text-xs mt-0 max-sm:text-center">
                <p>
                  This is a custom component written in Next and registered with
                  Builder. You can register any code components for
                  drag-and-drop editing.
                </p>
              </div>
              <img
                loading="lazy"
                sizes="(max-width: 998px) 11vw, 8vw"
                src="https://cdn.builder.io/api/v1/image/assets%2F8d9ee72a33344b4b867918b442ebd0af%2Fdd6e201535a748229aa374f04e14eaea"
                className="aspect-[2.88] object-contain object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden max-w-[102px] ml-auto mt-5 max-md:flex max-sm:hidden"
              />
            </div>

            <Counter
              className="flex flex-col relative shrink-0 box-border max-w-[50%] w-full pr-5 max-sm:mx-auto"
              initialValue={99}
              initialCount={50}
            />
          </div>
          <div className="flex flex-row relative shrink-0 box-border justify-center w-full self-center max-w-[700px] gap-7 flex-wrap mt-10 max-md:w-full max-md:max-w-[450px] max-sm:flex max-sm:flex-col max-sm:items-center">
            <a
              href="https://www.builder.io/c/docs/integrating-builder-pages#creating-a-builder-page"
              target="_blank"
              className="flex flex-col relative shrink-0 box-border justify-between cursor-pointer pointer-events-auto w-full overflow-hidden max-sm:items-center max-sm:max-w-[300px]"
            >
              <div className="flex flex-col relative shrink-0 box-border border overflow-hidden pb-5 rounded-lg border-solid border-black">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F238f66e07d3049eaa5d93b56b86c6579?"
                  className="aspect-[2.22] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden"
                />
                <div className="relative shrink-0 box-border h-auto text-black font-semibold text-center mt-2.5 mb-2.5 px-2.5">
                  <p>Create Builder pages in your app</p>
                </div>
                <div className="relative shrink-0 box-border h-auto text-black text-center text-xs w-full max-w-[450px] mt-0 mx-auto px-2.5 max-sm:text-center">
                  <p>
                    This is an example page created in Builder. Start here to
                    review how your integration works and create new pages in
                    your app.
                  </p>
                </div>
              </div>
            </a>
            <a
              href="https://www.builder.io/c/docs/custom-components-intro"
              target="_blank"
              className="flex flex-col relative shrink-0 box-border justify-between max-w-[48%] cursor-pointer pointer-events-auto overflow-hidden max-md:max-w-full max-md:w-full max-sm:items-center max-sm:max-w-[300px]"
            >
              <div className="flex flex-col relative shrink-0 box-border border overflow-hidden pb-5 rounded-lg border-solid border-black">
                <div className="flex flex-col relative shrink-0 box-border bg-slate-900">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263"
                    className="aspect-[3.3] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden"
                  />
                </div>
                <div className="relative shrink-0 box-border h-auto text-black font-semibold text-center mt-2.5 mb-2.5 px-2.5">
                  <p>Register your Next components </p>
                </div>
                <div className="relative shrink-0 box-border h-auto text-black text-center text-xs mt-0 px-2.5 max-sm:text-center">
                  <p>
                    Register your Next.js components in Builder. You can drag
                    and drop any custom component from the Visual Editor onto a
                    page.
                  </p>
                </div>
              </div>
            </a>
            <a
              href="https://www.builder.io/c/blueprints"
              target="_blank"
              className="flex flex-col relative shrink-0 box-border justify-between max-w-[48%] border cursor-pointer pointer-events-auto overflow-hidden pb-5 rounded-lg border-solid border-black max-md:max-w-full max-md:w-full max-sm:items-center max-sm:max-w-[300px]"
            >
              <div className="flex flex-col relative shrink-0 box-border">
                <div className="flex flex-col relative shrink-0 box-border bg-zinc-900 items-center justify-center pt-2.5 pb-9 px-2.5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=2000"
                    className="aspect-[2.92] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden max-w-[170px]"
                  />
                </div>
                <div className="relative shrink-0 box-border h-auto text-black font-semibold text-center mt-2.5 mb-2.5 px-2.5">
                  <p>Integrate common use cases</p>
                </div>
                <div className="relative shrink-0 box-border h-auto text-black text-center text-xs mt-0 px-2.5 max-sm:text-center">
                  <p>
                    Reference how you can use Builder for your blog, eCommerce
                    product listings, or for your entire site.
                  </p>
                </div>
              </div>
            </a>
            <a
              href="https://www.builder.io/c/docs/ui-ve-tour"
              target="_blank"
              className="flex flex-col relative shrink-0 box-border justify-between max-w-[48%] cursor-pointer pointer-events-auto overflow-hidden max-md:max-w-full max-md:w-full max-sm:items-center max-sm:max-w-[300px]"
            >
              <div className="flex flex-col relative shrink-0 box-border border pointer-events-auto h-full overflow-hidden pb-5 rounded-lg border-solid border-black">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58"
                  className="aspect-[2.22] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden"
                />
                <div className="relative shrink-0 box-border h-auto text-black font-semibold text-center mt-2.5 mb-2.5 px-2.5">
                  <p>Tour the Visual Editor </p>
                </div>
                <div className="relative shrink-0 box-border h-auto text-black text-center text-xs mt-0 px-2.5 max-sm:text-center">
                  <p>
                    Check out the UI of the Visual Editor and compose complex
                    layouts without writing any code.
                  </p>
                </div>
              </div>
            </a>
            <a
              href="https://www.builder.io/c/docs/block-types"
              target="_blank"
              className="flex flex-col relative shrink-0 box-border justify-between max-w-[48%] cursor-pointer pointer-events-auto overflow-hidden max-md:max-w-full max-md:w-full max-sm:items-center max-sm:max-w-[300px]"
            >
              <div className="flex flex-col relative shrink-0 box-border border pointer-events-auto overflow-hidden pb-5 rounded-lg border-solid border-black">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9"
                  className="aspect-[2.22] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden"
                />
                <div className="relative shrink-0 box-border h-auto text-black font-semibold text-center mt-2.5 mb-2.5 px-2.5">
                  <p>Learn the building blocks</p>
                </div>
                <div className="relative shrink-0 box-border h-auto text-black text-center text-xs mt-0 px-2.5 max-sm:text-center">
                  <p>
                    Creating content in Builder uses a flexible toolset of
                    no-code blocks that you can use to create almost anything.
                  </p>
                </div>
              </div>
            </a>
          </div>
        </section>
      </div>
      <div
        className="builder-footer flex flex-col relative shrink-0 box-border min-h-[100px] text-white bg-black w-screen self-stretch ml-[calc(50%_-_50vw)] pt-8 pb-10 px-5 max-sm:pt-5"
      >
        <section className="builder-footer flex flex-col relative shrink-0 box-border min-h-[100px] text-white bg-black w-full self-stretch grow max-w-[1200px] items-stretch mx-auto pt-8 pb-10 px-5 max-sm:pt-5">
          <div className="flex flex-col relative shrink-0 box-border w-full max-w-[600px] mt-5 mx-auto">
            <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
              <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
                <div className="flex flex-col relative shrink-0 box-border max-md:items-center">
                  <div className="flex flex-col relative shrink-0 box-border">
                    <div className="relative shrink-0 box-border h-auto text-white font-semibold text-left text-base">
                      <p>Integrating Builder with your app</p>
                    </div>
                    <div className="flex flex-col relative shrink-0 box-border gap-2.5 leading-relaxed pt-2.5">
                      <a
                        href="https://www.builder.io/c/docs/how-builder-works-technical"
                        target="_blank"
                        className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                      >
                        <p>How Builder Works</p>
                      </a>
                      <a
                        href="https://www.builder.io/c/docs/integrate-symbols"
                        target="_blank"
                        className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                      >
                        <p>Integrate Symbols</p>
                      </a>
                      <a
                        href="https://www.builder.io/c/docs/integrate-cms-data"
                        target="_blank"
                        className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                      >
                        <p>Using Builder CMS data</p>
                      </a>
                      <a
                        href="https://www.builder.io/c/docs/api-intro"
                        target="_blank"
                        className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                      >
                        <p>Builder API </p>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="flex flex-col relative shrink-0 box-border max-md:items-center max-md:mt-7">
                  <div className="relative shrink-0 box-border h-auto text-white font-semibold text-left text-base">
                    <p>Learn the Builder Visual Editor</p>
                  </div>
                  <div className="flex flex-col relative shrink-0 box-border gap-2.5 pt-2.5">
                    <a
                      href="https://www.builder.io/c/docs/how-builder-works"
                      target="_blank"
                      className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                    >
                      <p>Builder Docs</p>
                    </a>
                    <a
                      href="https://www.builder.io/c/docs/custom-components-intro"
                      target="_blank"
                      className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                    >
                      <p>Custom Components</p>
                    </a>
                    <a
                      href="https://www.builder.io/c/blueprints"
                      target="_blank"
                      className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                    >
                      <p>Blueprints</p>
                    </a>
                    <a
                      href="https://forum.builder.io/"
                      target="_blank"
                      className="relative shrink-0 box-border h-auto text-white text-left text-sm cursor-pointer pointer-events-auto max-md:text-center"
                    >
                      <p>Forum</p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}

export default MyComponent